[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
allow_untyped_globals = true
follow_imports = "silent"
ignore_missing_imports = true

[tool.ruff]
# Pyflakes (F), pycodestyle (E, W), isort (I)
select = ["E", "F", "I", "W"]
line-length = 100
extend-exclude = ["./*/migrations", "manage.py", "./node_modules"]

[tool.ruff.per-file-ignores]
"./airone/tests/test_elasticsearch.py" = ["E501"]

[tool.poetry]
name = "airone"
version = "3.73.0"
description = ""
authors = ["Hiroyasu OHYAMA"]
license = "GPLv2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "1.26.114"
celery = "5.2.2"
ddtrace = "2.1.1"
django-configurations = "2.3.2"
django-debug-toolbar = "3.2.4"
django-environ = "0.9.0"
django-filter = "2.4.0"
django-import-export = "2.5.0"
django-replicated = "2.7"
django-simple-history = "3.2.0"
django-storages = "1.13.2"
django = "3.2.25"
djangorestframework = "3.15.1"
drf-spectacular = "0.26.4"
elasticsearch = "7.17.6"
flower = "1.2.0"
gunicorn = "22.0.0"
kombu = "5.2.2"
mock = "2.0.0"
mysqlclient = "2.1.0"
natsort = "5.3.3"
python-ldap = "3.4.0"
python3-saml = "1.12.0"
pyyaml = "6.0.1"
requests = "2.31.0"
six = "1.15.0"
setproctitle = "1.3.2"
social-auth-app-django = "5.4.0"
social-auth-core = "4.5.1"
uritemplate = "3.0.1"
whitenoise = "5.2.0"


[tool.poetry.group.dev.dependencies]
coverage = "^7.3.0"
mypy = "^1.5.1"
requests-html = "0.10.0"
types-six = "^1.16.21.9"
types-requests = "^2.31.0.2"
types-pyyaml = "^6.0.12.11"
types-pytz = "^2023.3.0.1"
types-mock = "^5.1.0.1"
ruff = "^0.1.7"
tox = "^4.11.4"
tblib = "^3.0.0"
lxml-html-clean = "^0.1.1"
