name: deploy hugo
on:
  push:
    branches:
      - fixed/gh_pages

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
      - name: Build
        run: hugo --minify
        working-directory: ./docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
